package com.certcopilot.platform.ai;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Correction A2: the artifact key must change whenever anything that affects
 * output semantics changes, and must not change otherwise.
 */
class ArtifactKeyTest {

    private static final DomainValidator ALWAYS_OK =
            (raw, ctx) -> DomainValidator.ValidationResult.ok();

    private static AiOperation op(String promptVersion, String schemaVersion, String modelConfig) {
        return new AiOperation("op.test", promptVersion, schemaVersion, modelConfig,
                ModelTier.FAST, 500, 2, 3, ALWAYS_OK, true);
    }

    private static ArtifactKey key(AiOperation operation, String unitHash, String certVersion) {
        return ArtifactKey.of("LEARNING_PACK")
                .semantic("learningUnitContentHash", unitHash)
                .semantic("certificationVersionId", certVersion)
                .operation(operation)
                .build();
    }

    @Test
    @DisplayName("identical semantic input and generation version reuse the same key")
    void sameInputsProduceSameKey() {
        AiOperation operation = op("v1", "v1", "cfg-1");
        assertThat(key(operation, "unit-a", "cert-1").value())
                .isEqualTo(key(operation, "unit-a", "cert-1").value());
    }

    @Test
    @DisplayName("a changed semantic input produces a different key")
    void semanticChangeProducesNewKey() {
        AiOperation operation = op("v1", "v1", "cfg-1");
        assertThat(key(operation, "unit-a", "cert-1").value())
                .isNotEqualTo(key(operation, "unit-b", "cert-1").value());
        assertThat(key(operation, "unit-a", "cert-1").value())
                .isNotEqualTo(key(operation, "unit-a", "cert-2").value());
    }

    @Test
    @DisplayName("a changed prompt version produces a different key")
    void promptVersionChangeProducesNewKey() {
        assertThat(key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1").value())
                .isNotEqualTo(key(op("v2", "v1", "cfg-1"), "unit-a", "cert-1").value());
    }

    @Test
    @DisplayName("a changed output schema version produces a different key")
    void schemaVersionChangeProducesNewKey() {
        assertThat(key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1").value())
                .isNotEqualTo(key(op("v1", "v2", "cfg-1"), "unit-a", "cert-1").value());
    }

    @Test
    @DisplayName("a changed model configuration version produces a different key")
    void modelConfigChangeProducesNewKey() {
        assertThat(key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1").value())
                .isNotEqualTo(key(op("v1", "v1", "cfg-2"), "unit-a", "cert-1").value());
    }

    @Test
    @DisplayName("the two halves of the key are reported separately for debugging")
    void halvesAreSeparatelyAddressable() {
        ArtifactKey a = key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1");
        ArtifactKey b = key(op("v2", "v1", "cfg-1"), "unit-a", "cert-1");

        assertThat(a.semanticInputHash())
                .as("same content, so the semantic half must match")
                .isEqualTo(b.semanticInputHash());
        assertThat(a.generationVersionHash())
                .as("different prompt version, so the generation half must differ")
                .isNotEqualTo(b.generationVersionHash());
    }

    @Test
    @DisplayName("content generated by the fake never shares a key with a real model's")
    void theGeneratingModelIsPartOfTheKey() {
        ArtifactKey base = key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1");

        ArtifactKey fromFake = base.withGeneration("generator", "fake-quality-v1");
        ArtifactKey fromGemini = base.withGeneration("generator", "gemini:gemini-3.5-flash");

        assertThat(fromFake.semanticInputHash())
                .as("the artifact is about the same unit either way")
                .isEqualTo(fromGemini.semanticInputHash());
        assertThat(fromFake.value())
                .as("otherwise flipping AI_ADAPTER serves fixture prose under a provider's name")
                .isNotEqualTo(fromGemini.value());
        assertThat(base.value())
                .as("the caller's key is not the effective key")
                .isNotEqualTo(fromFake.value());
    }

    @Test
    @DisplayName("adding a generation input leaves the original key untouched")
    void withGenerationDoesNotMutate() {
        ArtifactKey base = key(op("v1", "v1", "cfg-1"), "unit-a", "cert-1");
        String before = base.value();

        base.withGeneration("generator", "gemini:gemini-3.5-flash");

        assertThat(base.value()).isEqualTo(before);
    }

    @Test
    @DisplayName("a key without a generation version is rejected")
    void generationVersionIsMandatory() {
        assertThatThrownBy(() -> ArtifactKey.of("LEARNING_PACK")
                .semantic("unit", "a")
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("generation version");
    }

    @Test
    @DisplayName("a key without semantic input is rejected")
    void semanticInputIsMandatory() {
        assertThatThrownBy(() -> ArtifactKey.of("LEARNING_PACK")
                .operation(op("v1", "v1", "cfg-1"))
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("semantic input");
    }
}
