package com.certcopilot.platform.ai;

import java.util.UUID;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Whether a plan's generated content came from a real model or from the
 * deterministic fake.
 *
 * <p>Exists because a coverage percentage computed from fixture output looks
 * exactly like a measured one, and is worth nothing. Anything the product
 * presents as a measurement has to be able to say where it came from.
 *
 * <p>Read from the cost ledger rather than from the currently configured
 * adapter, so a plan generated in development still reports itself as synthetic
 * after the server is restarted against a real provider. The alternative -
 * trusting today's configuration - is exactly how fixture numbers end up in a
 * demo.
 */
@Component
public class AiProvenance {

    public enum Source {
        /** Generated by a real provider. Measurements derived from it mean something. */
        MODEL,
        /** Generated by the deterministic fake. Present it as such or not at all. */
        SYNTHETIC,
        /** Nothing has been generated yet. */
        NONE
    }

    private final JdbcTemplate jdbc;

    public AiProvenance(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Transactional(readOnly = true)
    public Source forPlan(UUID planId) {
        if (planId == null) {
            return Source.NONE;
        }
        // Cache hits record no model, so they are excluded rather than counted
        // as real; a plan served entirely from a synthetic cache still has the
        // generating rows in its own ledger.
        Integer synthetic = jdbc.queryForObject(
                "SELECT count(*) FROM ai_call_ledger "
                        + " WHERE plan_id = ? AND outcome = 'SUCCESS' AND model LIKE ?",
                Integer.class, planId, LlmPort.SYNTHETIC_MODEL_PREFIX + "%");
        if (synthetic != null && synthetic > 0) {
            return Source.SYNTHETIC;
        }
        Integer real = jdbc.queryForObject(
                "SELECT count(*) FROM ai_call_ledger "
                        + " WHERE plan_id = ? AND outcome = 'SUCCESS' AND model <> '-' AND model NOT LIKE ?",
                Integer.class, planId, LlmPort.SYNTHETIC_MODEL_PREFIX + "%");
        return real != null && real > 0 ? Source.MODEL : Source.NONE;
    }
}
