import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import type { CompletionResult, PackView, QuizResponse, TodayItem, TodayView } from '../api/types'
import { BlockRenderer } from '../components/BlockRenderer'
import { SlidePanel } from '../components/SlidePanel'
import { Banner, EmptyState, ErrorState, InlineError, Loading } from '../components/states'

/**
 * The home screen, and the reason someone opens the product on day two.
 *
 * One job: answer "what do I study now" without asking the learner to decide
 * anything. Everything else on the page - the lesson, the source panel, the quiz
 * - hangs off that answer, which is why this is not a dashboard. Numbers appear
 * only where they change what the learner does next.
 */
export function TodayPage() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [openUnitId, setOpenUnitId] = useState<string | null>(null)
  const [source, setSource] = useState<{ materialId: string; start: number; end: number } | null>(
    null,
  )
  const [completion, setCompletion] = useState<CompletionResult | null>(null)

  const today = useQuery({
    queryKey: ['today'],
    queryFn: () => api.get<TodayView>('/api/v1/today'),
    // Content for the day is generated by a background worker. Poll until it
    // has landed, then stop - the learner should never have to reload to find
    // out that today is ready.
    refetchInterval: (query) => {
      const view = query.state.data
      if (!view?.hasPlan || view.planStatus !== 'ACTIVE' || !view.studyDayId) {
        return false
      }
      const contentPending =
        view.items.some((item) => item.learningUnitId && !item.packReady) || !view.quizAvailable
      return contentPending ? 2500 : false
    },
  })

  const startQuiz = useMutation({
    mutationFn: (kind: 'DAILY' | 'WARMUP' | 'FINAL_REVIEW') =>
      api.post<QuizResponse>(`/api/v1/plans/${today.data?.planId}/quizzes`, {
        kind,
        studyDayId: today.data?.studyDayId,
      }),
    onSuccess: (data) => navigate(`/quiz/${data.attempt.id}`),
  })

  const completeItem = useMutation({
    mutationFn: (itemId: string) =>
      api.post(`/api/v1/plans/${today.data?.planId}/items/${itemId}/complete`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['today'] }),
  })

  const completeDay = useMutation({
    mutationFn: () =>
      api.post<CompletionResult>(
        `/api/v1/plans/${today.data?.planId}/days/${today.data?.studyDayId}/complete`,
      ),
    onSuccess: (data) => {
      setCompletion(data)
      setOpenUnitId(null)
      queryClient.invalidateQueries({ queryKey: ['today'] })
      queryClient.invalidateQueries({ queryKey: ['progress'] })
      queryClient.invalidateQueries({ queryKey: ['plans'] })
    },
  })

  if (today.isPending) return <Loading />
  if (today.error) return <ErrorState error={today.error} onRetry={() => today.refetch()} />

  const view = today.data!

  if (!view.hasPlan) {
    return (
      <div className="page">
        <EmptyState
          icon="📅"
          title="Bạn chưa có kế hoạch học nào"
          hint="Tạo kế hoạch từ ngày thi và tài liệu khoá học của bạn, rồi mỗi sáng mở đúng màn hình này."
          action={
            <button type="button" onClick={() => navigate('/onboarding')}>
              Tạo kế hoạch học
            </button>
          }
        />
      </div>
    )
  }

  // COMPLETED is a finished schedule, not a half-built one: the learner still
  // has the final review exam ahead of them.
  if (view.planStatus !== 'ACTIVE' && view.planStatus !== 'COMPLETED') {
    return (
      <div className="page">
        <EmptyState
          icon="⏳"
          title="Kế hoạch đang được chuẩn bị"
          hint="Hệ thống vẫn đang đọc tài liệu của bạn. Quay lại bước thiết lập để xem tiến trình."
          action={
            <button type="button" onClick={() => navigate('/onboarding')}>
              Tiếp tục thiết lập
            </button>
          }
        />
      </div>
    )
  }

  if (!view.studyDayId) {
    return (
      <div className="page">
        <FinishedPlan view={view} onStartExam={() => startQuiz.mutate('FINAL_REVIEW')} />
        {startQuiz.error && <QuizStartError error={startQuiz.error} />}
      </div>
    )
  }

  const plannedMinutes = view.items.reduce((sum, item) => sum + item.allottedMinutes, 0)
  const doneMinutes = view.items
    .filter((item) => item.status === 'DONE')
    .reduce((sum, item) => sum + item.allottedMinutes, 0)

  return (
    <div className={`page today ${source ? 'with-source' : ''}`}>
      <div className="today-main">
        <header className="today-head">
          <div>
            <p className="eyebrow">
              Ngày {view.dayIndex} / {view.totalDays} · {formatDay(view.date)}
              {view.kind === 'REVIEW' ? ' · Ngày ôn tập' : ''}
            </p>
            <h1>Hôm nay</h1>
            <p className="today-load">
              <span>
                Dự kiến <strong>{formatMinutes(plannedMinutes)}</strong>
              </span>
              <span className="muted">·</span>
              <span>
                Đã xong <strong>{formatMinutes(doneMinutes)}</strong>
              </span>
            </p>
          </div>
          <div className="countdown">
            <strong>{view.daysUntilExam}</strong>
            <span>ngày tới kỳ thi</span>
          </div>
        </header>

        <div className="progressbar" aria-label={`Tiến độ kế hoạch ${pct(view.completedDays, view.totalDays)}%`}>
          <span style={{ width: `${pct(view.completedDays, view.totalDays)}%` }} />
        </div>

        {completion && (
          <CompletionSummary result={completion} onDismiss={() => setCompletion(null)} />
        )}

        {view.warmupAvailable > 0 && (
          <div className="warmup">
            <div>
              <strong>Ôn nhanh {Math.min(view.warmupAvailable, 3)} câu</strong>
              <p className="muted">
                Những câu bạn từng làm sai ở nội dung bắt buộc. Làm trước khi vào bài mới.
              </p>
            </div>
            <button type="button" className="ghost" onClick={() => startQuiz.mutate('WARMUP')}>
              Bắt đầu ôn
            </button>
          </div>
        )}

        <ol className="unit-timeline">
          {view.items.map((item) => (
            <UnitRow
              key={item.itemId}
              item={item}
              planId={view.planId!}
              expanded={openUnitId === item.learningUnitId}
              sourceOpen={Boolean(source)}
              onToggle={() =>
                setOpenUnitId(
                  openUnitId === item.learningUnitId ? null : (item.learningUnitId ?? null),
                )
              }
              onOpenSource={(start, end) =>
                item.materialId && setSource({ materialId: item.materialId, start, end })
              }
              onComplete={() => completeItem.mutate(item.itemId)}
            />
          ))}
        </ol>

        <footer className="today-actions">
          {view.quizAvailable ? (
            <button type="button" onClick={() => startQuiz.mutate('DAILY')}>
              Làm quiz hôm nay
            </button>
          ) : (
            <Banner tone="warn">
              Chưa tạo được câu hỏi cho hôm nay. Bạn vẫn có thể hoàn thành ngày học.
            </Banner>
          )}
          <button
            type="button"
            className="ghost"
            disabled={completeDay.isPending}
            onClick={() => completeDay.mutate()}
          >
            {completeDay.isPending ? 'Đang cập nhật…' : 'Hoàn thành ngày'}
          </button>
        </footer>

        {startQuiz.error && <QuizStartError error={startQuiz.error} />}
        {completeDay.error && <InlineError error={completeDay.error} />}
      </div>

      {source && (
        <SlidePanel
          materialId={source.materialId}
          pageStart={source.start}
          pageEnd={source.end}
          onClose={() => setSource(null)}
        />
      )}
    </div>
  )
}

/**
 * The plan is finished but the exam is not.
 *
 * The week between the last study day and the exam is exactly what the final
 * review exam is for, so this screen offers it rather than congratulating the
 * learner and sending them back to onboarding as though they had never had a
 * plan at all.
 */
function FinishedPlan({ view, onStartExam }: { view: TodayView; onStartExam: () => void }) {
  const navigate = useNavigate()
  const ready = view.finalExam?.ready ?? false

  return (
    <section className="finished-plan">
      <header className="page-head">
        <div>
          <p className="eyebrow">Lịch học đã xong</p>
          <h1>Bạn đã hoàn thành toàn bộ {view.totalDays} buổi</h1>
          <p className="muted">
            {view.daysUntilExam > 0
              ? `Còn ${view.daysUntilExam} ngày tới kỳ thi. Giai đoạn này để ôn tổng hợp và vá chỗ yếu.`
              : 'Kỳ thi đã tới. Kế hoạch này vẫn ở lại để bạn xem lại bất cứ lúc nào.'}
          </p>
        </div>
      </header>

      <div className="finished-actions">
        <div className="card">
          <h2>Bài ôn tổng hợp</h2>
          {ready ? (
            <>
              <p className="muted">
                Đề được lắp từ {view.finalExam?.bankSize} câu đã qua kiểm tra, chọn theo trọng số
                domain chính thức.
              </p>
              <button type="button" onClick={onStartExam}>
                Làm bài ôn tổng hợp
              </button>
            </>
          ) : (
            <Banner tone="info">
              Ngân hàng câu hỏi hiện có {view.finalExam?.bankSize ?? 0} câu, cần{' '}
              {view.finalExam?.minimumRequired ?? 0} câu để mở bài ôn tổng hợp.
            </Banner>
          )}
        </div>

        <div className="card">
          <h2>Tiếp theo</h2>
          <ul className="next-actions">
            <li>
              <button type="button" className="ghost" onClick={() => navigate('/plan')}>
                Xem tiến độ và chủ đề còn yếu
              </button>
            </li>
            <li>
              <button type="button" className="ghost" onClick={() => navigate('/materials')}>
                Mở lại tài liệu gốc
              </button>
            </li>
            <li>
              <button type="button" className="ghost" onClick={() => navigate('/plans')}>
                Bắt đầu kế hoạch cho chứng chỉ khác
              </button>
            </li>
          </ul>
        </div>
      </div>
    </section>
  )
}

function UnitRow({
  item,
  planId,
  expanded,
  sourceOpen,
  onToggle,
  onOpenSource,
  onComplete,
}: {
  item: TodayItem
  planId: string
  expanded: boolean
  sourceOpen: boolean
  onToggle: () => void
  onOpenSource: (start: number, end: number) => void
  onComplete: () => void
}) {
  const pack = useQuery({
    queryKey: ['pack', planId, item.learningUnitId],
    enabled: expanded && Boolean(item.learningUnitId),
    queryFn: () => api.get<PackView>(`/api/v1/plans/${planId}/units/${item.learningUnitId}/pack`),
    // 202 means the worker is still generating; poll until it lands.
    refetchInterval: (query) => (query.state.data?.blocks ? false : 2000),
  })

  const isReview = item.type !== 'LEARNING_UNIT'
  const relevance = RELEVANCE[item.relevance] ?? null

  return (
    <li className={`unit ${item.status === 'DONE' ? 'done' : ''} ${expanded ? 'open' : ''}`}>
      <div className="unit-head">
        <div className="unit-title">
          <div className="unit-title-row">
            <strong>{item.title}</strong>
            {!isReview && relevance && (
              <span className={`chip ${relevance.tone}`}>{relevance.label}</span>
            )}
            {isReview && <span className="chip">Ôn tập</span>}
            {item.hasSignificantVisual && (
              <span className="chip warn" title="Phần này có sơ đồ; nên xem slide gốc">
                có sơ đồ
              </span>
            )}
          </div>
          <span className="muted">
            {formatMinutes(item.allottedMinutes)}
            {item.pageStart ? ` · trang ${item.pageStart}–${item.pageEnd}` : ''}
          </span>
        </div>
        <div className="unit-actions">
          {item.pageStart && item.materialId && (
            <button
              type="button"
              className="ghost small"
              onClick={() => onOpenSource(item.pageStart!, item.pageEnd ?? item.pageStart!)}
            >
              Slide gốc
            </button>
          )}
          {!isReview && (
            <button type="button" className="ghost small" onClick={onToggle}>
              {expanded ? 'Thu gọn' : 'Mở bài giảng'}
            </button>
          )}
          {item.status !== 'DONE' ? (
            <button type="button" className="small" onClick={onComplete}>
              Xong
            </button>
          ) : (
            <span className="chip good">Đã xong</span>
          )}
        </div>
      </div>

      {expanded && (
        <div className="unit-body">
          {pack.isPending && <Loading label="Đang chuẩn bị bài giảng…" />}
          {pack.error && <ErrorState error={pack.error} onRetry={() => pack.refetch()} />}
          {pack.data?.blocks && (
            <>
              <div className="lesson-toolbar">
                <span className="muted">
                  Bài giảng do AI tạo từ tài liệu của bạn — bản đi kèm, không thay thế slide gốc.
                </span>
                {item.materialId && item.pageStart && !sourceOpen && (
                  <button
                    type="button"
                    className="ghost small"
                    onClick={() => onOpenSource(item.pageStart!, item.pageEnd ?? item.pageStart!)}
                  >
                    Mở slide gốc bên cạnh
                  </button>
                )}
              </div>
              <BlockRenderer blocks={pack.data.blocks} onOpenSource={onOpenSource} />
            </>
          )}
        </div>
      )}
    </li>
  )
}

function CompletionSummary({
  result,
  onDismiss,
}: {
  result: CompletionResult
  onDismiss: () => void
}) {
  if (result.scheduleInfeasible && result.infeasible) {
    return (
      <div className="banner danger">
        <strong>Lịch còn lại không còn khả thi.</strong>
        <ul>
          {result.infeasible.suggestions.map((s) => (
            <li key={s.code}>{s.detail}</li>
          ))}
        </ul>
      </div>
    )
  }
  return (
    <div className="banner good">
      <strong>Đã hoàn thành ngày học.</strong>
      {result.weakTopics.length > 0 && (
        <p>
          Phát hiện {result.weakTopics.length} chủ đề cần ôn lại:{' '}
          {result.weakTopics.map((w) => w.title).join(', ')}. Đã chèn vào lịch trước nội dung mới.
        </p>
      )}
      {result.nextDayDate && <p>Buổi tiếp theo: {formatDay(result.nextDayDate)}.</p>}
      <button type="button" className="ghost small" onClick={onDismiss}>
        Đã hiểu
      </button>
    </div>
  )
}

function QuizStartError({ error }: { error: unknown }) {
  if (error instanceof ApiError && error.code === 'NO_WARMUP') {
    return <Banner tone="info">{error.message}</Banner>
  }
  if (error instanceof ApiError && error.code === 'QUIZ_UNAVAILABLE') {
    return <Banner tone="warn">{error.message}</Banner>
  }
  return <InlineError error={error} />
}

const RELEVANCE: Record<string, { label: string; tone: string }> = {
  CRITICAL: { label: 'BẮT BUỘC', tone: 'critical' },
  HIGH: { label: 'QUAN TRỌNG', tone: 'high' },
  MEDIUM: { label: 'NÊN BIẾT', tone: '' },
  LOW: { label: 'ÍT GẶP', tone: '' },
  OPTIONAL: { label: 'NGOÀI PHẠM VI', tone: '' },
}

function pct(part: number, total: number): number {
  return total === 0 ? 0 : Math.round((part / total) * 100)
}

export function formatMinutes(minutes: number): string {
  if (minutes < 60) return `${minutes} phút`
  const hours = Math.floor(minutes / 60)
  const rest = minutes % 60
  return rest === 0 ? `${hours} giờ` : `${hours}h ${rest}m`
}

export function formatDay(iso?: string): string {
  if (!iso) return ''
  const date = new Date(`${iso}T00:00:00`)
  if (Number.isNaN(date.getTime())) return iso
  const weekday = ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'][date.getDay()]
  return `${weekday}, ${String(date.getDate()).padStart(2, '0')}/${String(
    date.getMonth() + 1,
  ).padStart(2, '0')}`
}
