import { test, expect } from '@playwright/test'
import { answerWholeQuiz, createPlanThroughWizard, register } from './helpers'

/**
 * The core learning loop, driven through the real browser against the real
 * backend and a real PostgreSQL.
 *
 * One test, end to end: register, choose the certification, set a deadline, see
 * the capacity check, upload a real PDF, watch the named pipeline stages,
 * activate the plan, open the Vietnamese lesson, look at the original slide,
 * take the grounded quiz, get graded, and complete the day so the schedule
 * adjusts.
 *
 * If this passes, the product exists. If it fails, nothing else matters.
 *
 * Prerequisites: the local stack from `scripts/dev-up`, and the backend running
 * on :8080. The sample deck is generated by that script.
 */
test('a learner goes from signup to a graded quiz and an adjusted plan', async ({ page }) => {
  await register(page, 'e2e')

  // A brand-new account has nothing, so it lands in the wizard rather than on
  // an empty Today it would have to escape from.
  await expect(page).toHaveURL(/\/onboarding/)

  await createPlanThroughWizard(page, 28)

  // ---- today -------------------------------------------------------------
  await expect(page.locator('.countdown strong')).toBeVisible()
  await expect(page.locator('.today-load')).toContainText('Dự kiến')
  const firstUnit = page.locator('.unit').first()
  await expect(firstUnit).toBeVisible()

  // ---- the Vietnamese lesson, and its link back to the slide -------------
  await firstUnit.getByRole('button', { name: 'Mở bài giảng' }).click()
  await expect(page.locator('.pack .block').first()).toBeVisible({ timeout: 90_000 })

  // Companion positioning: generated content is labelled and traceable.
  await expect(page.getByText(/Bài giảng do AI tạo/)).toBeVisible()
  await expect(page.locator('.block .source-link').first()).toBeVisible()

  // ---- original slide panel ----------------------------------------------
  await page.locator('.block .source-link').first().click()
  await expect(page.locator('.slide-panel')).toBeVisible()
  await expect(page.locator('.slide-panel')).toContainText('Tài liệu gốc')
  await page.locator('.slide-panel').getByRole('button', { name: 'Đóng' }).click()

  // ---- quiz --------------------------------------------------------------
  await page.getByRole('button', { name: 'Làm quiz hôm nay' }).click()
  await expect(page.getByRole('heading', { name: /^Câu 1 \// })).toBeVisible({ timeout: 90_000 })

  // The AI-generated notice is always present and never dismissible.
  await expect(page.locator('.ai-notice')).toContainText('không phải đề thi chính thức')

  // Submitting with questions unanswered must be impossible, not merely graded
  // as wrong: a half-answered multiple-response teaches the learner nothing.
  const pips = await page.locator('.quiz-pip').count()
  if (pips > 1) {
    await page.locator('.quiz-pip').last().click()
    await expect(page.getByRole('button', { name: 'Nộp bài' })).toBeDisabled()
    await page.locator('.quiz-pip').first().click()
  }

  await answerWholeQuiz(page)

  // ---- graded, with explanation and the source it came from --------------
  await expect(page.locator('.score strong')).toBeVisible()
  await expect(page.locator('.explanation').first()).toContainText('Vì sao đúng')
  await expect(page.locator('.source-span').first()).toContainText('Căn cứ')
  await expect(page.locator('.option-review.correct').first()).toContainText('Đáp án đúng')

  // ---- complete the day, which closes the loop ---------------------------
  await page.getByRole('button', { name: 'Quay lại Hôm nay' }).click()
  await expect(page.getByRole('heading', { name: 'Hôm nay', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Hoàn thành ngày' }).click()
  await expect(page.getByText('Đã hoàn thành ngày học.')).toBeVisible({ timeout: 90_000 })

  // ---- the plan reflects it ----------------------------------------------
  await page.getByRole('link', { name: 'Lịch & tiến độ' }).click()
  await expect(page.getByRole('heading', { name: 'Lịch & tiến độ' })).toBeVisible()
  await expect(page.locator('.day.completed').first()).toBeVisible()

  await page.getByRole('button', { name: 'Tiến độ' }).click()
  await expect(page.getByText('Buổi đã hoàn thành')).toBeVisible()
  await expect(page.getByText('Theo domain của kỳ thi')).toBeVisible()
})
