import { test, expect } from '@playwright/test'
import { aiProvider, answerWholeQuiz, createPlanThroughWizard, register, waitFor } from './helpers'

/**
 * The browser flow against a backend running on the real Gemini API.
 *
 * Opt-in, and skipped otherwise: it spends the account's tokens, so it must not
 * run as part of an ordinary `npm run e2e`. Start the backend with
 * `AI_ADAPTER=gemini` and a credential, then:
 *
 *   GEMINI_LIVE=1 npx playwright test e2e/gemini-live.spec.ts
 *
 * What this proves that the backend live test cannot: that a learner sitting in
 * front of the browser sees Gemini's own output. The lesson blocks and the quiz
 * questions rendered here were generated by the provider during this run - there
 * is no fixture, no stub server and no recorded response anywhere in the path,
 * and the assertions below fail rather than fall back if the provider is absent.
 *
 * The deck is synthetic, so this is an integration proof. It is not the
 * real-material evaluation, which needs a real AIF-C01 deck and a reviewer.
 */
test.skip(
  () => process.env.GEMINI_LIVE !== '1',
  'live Gemini browser flow is opt-in: set GEMINI_LIVE=1 and run the backend with AI_ADAPTER=gemini',
)

// A live model answers in tens of seconds, a plan is dozens of calls, and a free
// tier adds rate-limit pauses on top.
test.setTimeout(1_800_000)

test('the browser shows a plan whose lesson and quiz came from Gemini', async ({ page }) => {
  await register(page, 'gemini')

  // ---- the product must say which provider it is on ----------------------
  const meta = await aiProvider(page)
  expect(
    meta.aiProvider,
    'the backend is not running on Gemini; this test refuses to certify the fake adapter',
  ).toBe('GEMINI')
  expect(meta.aiSynthetic).toBe(false)
  expect(meta.fastModel).toMatch(/^gemini/)
  expect(meta.qualityModel).toMatch(/^gemini/)

  await page.goto('/plans')
  await expect(page.locator('.ai-chip')).toContainText('Gemini')
  await expect(page.locator('.ai-chip')).toContainText('Đã kết nối')
  await expect(page.locator('.ai-chip.live')).toBeVisible()

  // The synthetic banner exists precisely so nobody mistakes fixture prose for a
  // lesson. On a real provider it must be gone.
  await expect(page.locator('.dev-banner')).toHaveCount(0)

  // ---- the whole plan, built by Gemini -----------------------------------
  await page.getByRole('button', { name: /Kế hoạch mới|Tạo kế hoạch học/ }).click()
  await createPlanThroughWizard(page, 21)

  // With a real model the mapping is real, so the coverage number is one the
  // product is willing to stand behind.
  await page.getByRole('link', { name: 'Lịch & tiến độ' }).click()
  await page.getByRole('button', { name: 'Tiến độ' }).click()
  await expect(page.getByText('Mapping mô phỏng')).toHaveCount(0)

  // ---- the lesson on screen is Gemini's ----------------------------------
  await page.getByRole('link', { name: 'Hôm nay' }).click()
  const firstUnit = page.locator('.unit').first()
  await firstUnit.getByRole('button', { name: 'Mở bài giảng' }).click()
  await expect(page.locator('.pack .block').first()).toBeVisible({ timeout: waitFor(180_000) })

  const lessonText = await page.locator('.pack').innerText()
  expect(lessonText.length, 'a real lesson is prose, not a stub').toBeGreaterThan(400)
  await expect(page.locator('.block .source-link').first()).toBeVisible()

  // ---- and so is the quiz -------------------------------------------------
  await page.getByRole('button', { name: 'Làm quiz hôm nay' }).click()
  await answerWholeQuiz(page)
  await expect(page.locator('.explanation').first()).toContainText('Vì sao đúng')
  await expect(page.locator('.source-span').first()).toContainText('Căn cứ')

  // ---- the ledger must show real provider tokens, not a cache of nothing --
  const usage = await page.evaluate(async () => {
    const headers = { Authorization: `Bearer ${localStorage.getItem('certcopilot.accessToken')}` }
    const today = await fetch('/api/v1/today', { headers }).then((r) => r.json())
    return fetch(`/api/v1/plans/${today.planId}/ai-usage`, { headers }).then((r) => r.json())
  })

  // Provenance is read from what generated this plan, not from what the server
  // is configured with, so this cannot pass on a plan the fake adapter built.
  expect(usage.provenance).toBe('MODEL')
  expect(usage.models.every((model: string) => model.startsWith('gemini'))).toBe(true)
  expect(usage.tokensIn).toBeGreaterThan(0)
  expect(usage.tokensOut).toBeGreaterThan(0)
  expect(usage.providerCalls).toBeGreaterThan(0)

  // ---- and the same numbers are visible to the learner --------------------
  await page.goto('/settings')
  await expect(page.getByText('Mô hình thật')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Chế độ AI' })).toBeVisible()
})
